`timescale 1ns / 1ps

// FPGA Top-Level Wrapper for rv32i_top_p10
// Target : Digilent Zybo Z7-10 (xc7z010clg400-1)

module rv32i_fpga_top (
    input  wire clk,   // K17 - 125 MHz on-board clock
    input  wire rst,   // K18 - BTN0 (active-HIGH reset)

    // 4 on-board LEDs - show alu_out[3:0] as a quick sanity check
    output wire [3:0] led
);

    // Internal signals marked for ILA capture 
    (* mark_debug = "true", dont_touch = "true" *) wire [31:0] alu_out;
    (* mark_debug = "true", dont_touch = "true" *) wire [31:0] pc_out;

    // Additional internal signals to probe 
     (* mark_debug = "true", dont_touch = "true" *) wire        cache_stall;
     (* mark_debug = "true", dont_touch = "true" *) wire [31:0] hit_l1_count;
     (* mark_debug = "true", dont_touch = "true" *) wire [31:0] hit_vc_count;
     (* mark_debug = "true", dont_touch = "true" *) wire [31:0] miss_total_count;
     (* mark_debug = "true", dont_touch = "true" *) wire [31:0] mem_access_count;

    // CREATE A WIRE FOR SLOW CLOCK 
    wire slow_clk;

    // Instantiate the Clocking Wizard 
    clk_wiz_0 CLK_MANAGER (
        .clk_in1  (clk),       // 125 MHz physical clock from Zybo board
        .clk_out1 (slow_clk)   // Slowed down clock generated by the wizard
    );

    // Instantiate the P10 processor 
    rv32i_top_p10 DUT (
        .clk    (slow_clk),
        .rst    (rst),
        .alu_out(alu_out),
        .pc_out (pc_out)
    );

    // LED: show alu_out[3:0] for quick visual check 
    assign led = alu_out[3:0];

    // =========================================================
    // HARDWARE CYCLE & INSTRUCTION COUNTER FOR CPI ANALYSIS
    // =========================================================
    (* mark_debug = "true", dont_touch = "true" *) reg [31:0] total_cycles;
    (* mark_debug = "true", dont_touch = "true" *) reg [31:0] instruction_count; 
    (* mark_debug = "true", dont_touch = "true" *) reg program_done;             
    
    reg [31:0] prev_pc_reg;
    reg [7:0]  stagnation_timer; // NEW: To ignore temporary pipeline stalls!

    always @(posedge slow_clk) begin
        if (rst) begin
            total_cycles <= 0;
            instruction_count <= 0;
            prev_pc_reg <= 32'hFFFFFFFF;
            stagnation_timer <= 0;
            program_done <= 0;
        end else if (!program_done) begin
            total_cycles <= total_cycles + 1;
            prev_pc_reg <= pc_out;
            
            if (pc_out != prev_pc_reg && prev_pc_reg != 32'hFFFFFFFF) begin
                // PC advanced! Count the fetch and reset the stall timer.
                instruction_count <= instruction_count + 1;
                stagnation_timer <= 0; 
            end else if (pc_out == prev_pc_reg && prev_pc_reg != 32'hFFFFFFFF) begin
                // PC is frozen. Could be a 1-cycle hazard or 20-cycle cache miss.
                stagnation_timer <= stagnation_timer + 1; 
            end
            
            // Only trigger program_done if the PC has been frozen for 50 cycles!
            // This safely bypasses hazards and main memory cache misses.
            if (stagnation_timer == 50) begin
                program_done <= 1;
                total_cycles <= total_cycles - 50; // Rewind the 50 dead cycles for perfect accuracy
            end
        end
    end

endmodule